# Providers configuration - specify which providers to use
providers = ["python"]

[variables]
# Build-time variables for faster installation
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[python]
# Python configuration
version = "3.11"

[phases.setup]
# Setup phase - install system dependencies for OpenCV and image processing
cmds = [
    "apt-get update -qq",
    "apt-get install -y --no-install-recommends libglib2.0-0 libsm6 libxext6 libxrender1 libgomp1 libglib2.0-dev pkg-config libfontconfig1 libxss1"
]

[phases.install]
# Install phase - optimized pip installation
cmds = [
    "python -m pip install --upgrade pip wheel setuptools",
    "python -m pip install -r requirements.txt"
]

[phases.build]
# Build phase - prepare application
cmds = [
    "mkdir -p /tmp/pixport/uploads",
    "mkdir -p /tmp/pixport/processed"
]

[start]
# Start command
cmd = "gunicorn -c gunicorn.conf.py wsgi:app"
