[phases.build]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python download_models.py"
]

[phases.setup]
nixPkgs = ["python311", "libGL", "libglib"]

[variables]
PYTHONUNBUFFERED = "1"
NIXPACKS_PYTHON_VERSION = "3.11"
