[build]
# Build configuration for Railway - supports both main app and ISNet Tiny service
builder = "nixpacks"

[build.nixpacks]
# Use Python 3.11 for better compatibility
pythonVersion = "3.11"

[build.env]
# Build environment variables
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
# Memory optimization for Railway 512MB limit
MALLOC_ARENA_MAX = "2"
MALLOC_MMAP_THRESHOLD_ = "131072"
MALLOC_TRIM_THRESHOLD_ = "131072"

[deploy]
# Deployment configuration
healthcheckPath = "/api/bg/health"
healthcheckTimeout = 300
# Default: Full PixPort app with gunicorn
startCommand = "gunicorn -c gunicorn.conf.py wsgi:app"
# Alternative: ISNet Tiny service (uncomment to use)
# startCommand = "python app_isnet_tiny.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
# Production environment variables
FLASK_ENV = "production"
RAILWAY_ENVIRONMENT_NAME = "production"
REMBG_MODEL = "isnet-general-use"
# Memory optimization
MAX_CONTENT_LENGTH = "8388608"  # 8MB limit
# Directories for Railway ephemeral storage
UPLOAD_FOLDER = "/tmp/uploads"
PROCESSED_FOLDER = "/tmp/processed"

[environments.production.deploy]
# Production-specific deployment settings
replicas = 1

# ==== ISNet Tiny Service Configuration ====
# Uncomment this section to deploy the ultra-lightweight ISNet Tiny service
# instead of the full PixPort application

# [environments.isnet-tiny.variables]
# FLASK_ENV = "production"
# RAILWAY_ENVIRONMENT_NAME = "isnet-tiny"
# REMBG_MODEL = "isnet-general-tiny"
# MAX_CONTENT_LENGTH = "8388608"
# UPLOAD_FOLDER = "/tmp/uploads"
# PROCESSED_FOLDER = "/tmp/processed"
# PYTHONPATH = "/app"

# [environments.isnet-tiny.deploy]
# startCommand = "python app_isnet_tiny.py"
# healthcheckPath = "/api/bg/health"
# healthcheckTimeout = 300
# replicas = 1
# restartPolicyType = "ON_FAILURE"
# restartPolicyMaxRetries = 3

# ==== Deployment Instructions ====
# 
# Option 1: Full PixPort App (default)
# - Uses main app.py with multiple models and fallbacks
# - Memory usage: ~350MB peak
# - Features: Full passport photo processing + background removal
# 
# Option 2: ISNet Tiny Service (memory optimized)
# - Uncomment the isnet-tiny environment section above
# - Comment out the production startCommand and uncomment the alternative
# - Uses only isnet-general-tiny model
# - Memory usage: ~235MB peak
# - Features: Background removal + color change only
#
# To switch to ISNet Tiny:
# 1. Uncomment [environments.isnet-tiny.*] sections
# 2. Change deploy.startCommand to: python app_isnet_tiny.py
# 3. Deploy with: railway up --environment isnet-tiny
