[build]
# Build configuration for Railway
builder = "nixpacks"

[build.nixpacks]
# Use Python 3.11 for better compatibility
pythonVersion = "3.11"

[build.env]
# Build environment variables
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[deploy]
# Deployment configuration
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "gunicorn -c gunicorn.conf.py wsgi:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
# Production environment variables
FLASK_ENV = "production"
RAILWAY_ENVIRONMENT_NAME = "production"
REMBG_MODEL = "isnet-general-use"

[environments.production.deploy]
# Production-specific deployment settings
replicas = 1
